language: php

php:
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - cp .env.example .env
  - php artisan key:generate
  - php artisan storage:link

script:
  - vendor/bin/phpunit
